/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cat.diba.materialesportiu.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ActivityDependsOn service. Represents a row in the &quot;PME_ActivityDependsOn&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cat.diba.materialesportiu.model.impl.ActivityDependsOnModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cat.diba.materialesportiu.model.impl.ActivityDependsOnImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ActivityDependsOn
 * @see cat.diba.materialesportiu.model.impl.ActivityDependsOnImpl
 * @see cat.diba.materialesportiu.model.impl.ActivityDependsOnModelImpl
 * @generated
 */
@ProviderType
public interface ActivityDependsOnModel extends BaseModel<ActivityDependsOn>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a activity depends on model instance should use the {@link ActivityDependsOn} interface instead.
	 */

	/**
	 * Returns the primary key of this activity depends on.
	 *
	 * @return the primary key of this activity depends on
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this activity depends on.
	 *
	 * @param primaryKey the primary key of this activity depends on
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the activity depends on ID of this activity depends on.
	 *
	 * @return the activity depends on ID of this activity depends on
	 */
	public long getActivityDependsOnId();

	/**
	 * Sets the activity depends on ID of this activity depends on.
	 *
	 * @param activityDependsOnId the activity depends on ID of this activity depends on
	 */
	public void setActivityDependsOnId(long activityDependsOnId);

	/**
	 * Returns the activity ID of this activity depends on.
	 *
	 * @return the activity ID of this activity depends on
	 */
	public long getActivityId();

	/**
	 * Sets the activity ID of this activity depends on.
	 *
	 * @param activityId the activity ID of this activity depends on
	 */
	public void setActivityId(long activityId);

	/**
	 * Returns the parent activity ID of this activity depends on.
	 *
	 * @return the parent activity ID of this activity depends on
	 */
	public long getParentActivityId();

	/**
	 * Sets the parent activity ID of this activity depends on.
	 *
	 * @param parentActivityId the parent activity ID of this activity depends on
	 */
	public void setParentActivityId(long parentActivityId);

	/**
	 * Returns the quantity of this activity depends on.
	 *
	 * @return the quantity of this activity depends on
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this activity depends on.
	 *
	 * @param quantity the quantity of this activity depends on
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the group ID of this activity depends on.
	 *
	 * @return the group ID of this activity depends on
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this activity depends on.
	 *
	 * @param groupId the group ID of this activity depends on
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this activity depends on.
	 *
	 * @return the company ID of this activity depends on
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this activity depends on.
	 *
	 * @param companyId the company ID of this activity depends on
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this activity depends on.
	 *
	 * @return the user ID of this activity depends on
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this activity depends on.
	 *
	 * @param userId the user ID of this activity depends on
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this activity depends on.
	 *
	 * @return the user uuid of this activity depends on
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this activity depends on.
	 *
	 * @param userUuid the user uuid of this activity depends on
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this activity depends on.
	 *
	 * @return the user name of this activity depends on
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this activity depends on.
	 *
	 * @param userName the user name of this activity depends on
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this activity depends on.
	 *
	 * @return the create date of this activity depends on
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this activity depends on.
	 *
	 * @param createDate the create date of this activity depends on
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this activity depends on.
	 *
	 * @return the modified date of this activity depends on
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this activity depends on.
	 *
	 * @param modifiedDate the modified date of this activity depends on
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ActivityDependsOn activityDependsOn);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ActivityDependsOn> toCacheModel();

	@Override
	public ActivityDependsOn toEscapedModel();

	@Override
	public ActivityDependsOn toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}