/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cat.diba.materialesportiu.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Loan service. Represents a row in the &quot;PME_Loan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cat.diba.materialesportiu.model.impl.LoanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cat.diba.materialesportiu.model.impl.LoanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Loan
 * @see cat.diba.materialesportiu.model.impl.LoanImpl
 * @see cat.diba.materialesportiu.model.impl.LoanModelImpl
 * @generated
 */
@ProviderType
public interface LoanModel extends BaseModel<Loan>, GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loan model instance should use the {@link Loan} interface instead.
	 */

	/**
	 * Returns the primary key of this loan.
	 *
	 * @return the primary key of this loan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loan.
	 *
	 * @param primaryKey the primary key of this loan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loan ID of this loan.
	 *
	 * @return the loan ID of this loan
	 */
	public long getLoanId();

	/**
	 * Sets the loan ID of this loan.
	 *
	 * @param loanId the loan ID of this loan
	 */
	public void setLoanId(long loanId);

	/**
	 * Returns the local entity ID of this loan.
	 *
	 * @return the local entity ID of this loan
	 */
	public long getLocalEntityId();

	/**
	 * Sets the local entity ID of this loan.
	 *
	 * @param localEntityId the local entity ID of this loan
	 */
	public void setLocalEntityId(long localEntityId);

	/**
	 * Returns the pickup date of this loan.
	 *
	 * @return the pickup date of this loan
	 */
	public Date getPickupDate();

	/**
	 * Sets the pickup date of this loan.
	 *
	 * @param pickupDate the pickup date of this loan
	 */
	public void setPickupDate(Date pickupDate);

	/**
	 * Returns the return date of this loan.
	 *
	 * @return the return date of this loan
	 */
	public Date getReturnDate();

	/**
	 * Sets the return date of this loan.
	 *
	 * @param returnDate the return date of this loan
	 */
	public void setReturnDate(Date returnDate);

	/**
	 * Returns the activity date of this loan.
	 *
	 * @return the activity date of this loan
	 */
	public Date getActivityDate();

	/**
	 * Sets the activity date of this loan.
	 *
	 * @param activityDate the activity date of this loan
	 */
	public void setActivityDate(Date activityDate);

	/**
	 * Returns the activity name of this loan.
	 *
	 * @return the activity name of this loan
	 */
	@AutoEscape
	public String getActivityName();

	/**
	 * Sets the activity name of this loan.
	 *
	 * @param activityName the activity name of this loan
	 */
	public void setActivityName(String activityName);

	/**
	 * Returns the participants num of this loan.
	 *
	 * @return the participants num of this loan
	 */
	public int getParticipantsNum();

	/**
	 * Sets the participants num of this loan.
	 *
	 * @param participantsNum the participants num of this loan
	 */
	public void setParticipantsNum(int participantsNum);

	/**
	 * Returns the participants kids num of this loan.
	 *
	 * @return the participants kids num of this loan
	 */
	public int getParticipantsKidsNum();

	/**
	 * Sets the participants kids num of this loan.
	 *
	 * @param participantsKidsNum the participants kids num of this loan
	 */
	public void setParticipantsKidsNum(int participantsKidsNum);

	/**
	 * Returns the description of this loan.
	 *
	 * @return the description of this loan
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this loan.
	 *
	 * @param description the description of this loan
	 */
	public void setDescription(String description);

	/**
	 * Returns the contact person of this loan.
	 *
	 * @return the contact person of this loan
	 */
	@AutoEscape
	public String getContactPerson();

	/**
	 * Sets the contact person of this loan.
	 *
	 * @param contactPerson the contact person of this loan
	 */
	public void setContactPerson(String contactPerson);

	/**
	 * Returns the position person of this loan.
	 *
	 * @return the position person of this loan
	 */
	@AutoEscape
	public String getPositionPerson();

	/**
	 * Sets the position person of this loan.
	 *
	 * @param positionPerson the position person of this loan
	 */
	public void setPositionPerson(String positionPerson);

	/**
	 * Returns the telephone of this loan.
	 *
	 * @return the telephone of this loan
	 */
	@AutoEscape
	public String getTelephone();

	/**
	 * Sets the telephone of this loan.
	 *
	 * @param telephone the telephone of this loan
	 */
	public void setTelephone(String telephone);

	/**
	 * Returns the email of this loan.
	 *
	 * @return the email of this loan
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this loan.
	 *
	 * @param email the email of this loan
	 */
	public void setEmail(String email);

	/**
	 * Returns the pmt of this loan.
	 *
	 * @return the pmt of this loan
	 */
	@AutoEscape
	public String getPmt();

	/**
	 * Sets the pmt of this loan.
	 *
	 * @param pmt the pmt of this loan
	 */
	public void setPmt(String pmt);

	/**
	 * Returns the status of this loan.
	 *
	 * @return the status of this loan
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this loan.
	 *
	 * @param status the status of this loan
	 */
	public void setStatus(String status);

	/**
	 * Returns the group ID of this loan.
	 *
	 * @return the group ID of this loan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this loan.
	 *
	 * @param groupId the group ID of this loan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this loan.
	 *
	 * @return the company ID of this loan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loan.
	 *
	 * @param companyId the company ID of this loan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loan.
	 *
	 * @return the user ID of this loan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loan.
	 *
	 * @param userId the user ID of this loan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loan.
	 *
	 * @return the user uuid of this loan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this loan.
	 *
	 * @param userUuid the user uuid of this loan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loan.
	 *
	 * @return the user name of this loan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loan.
	 *
	 * @param userName the user name of this loan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loan.
	 *
	 * @return the create date of this loan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loan.
	 *
	 * @param createDate the create date of this loan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loan.
	 *
	 * @return the modified date of this loan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loan.
	 *
	 * @param modifiedDate the modified date of this loan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Loan loan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Loan> toCacheModel();

	@Override
	public Loan toEscapedModel();

	@Override
	public Loan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}