/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cat.diba.materialesportiu.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LoanActivity service. Represents a row in the &quot;PME_LoanActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cat.diba.materialesportiu.model.impl.LoanActivityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cat.diba.materialesportiu.model.impl.LoanActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoanActivity
 * @see cat.diba.materialesportiu.model.impl.LoanActivityImpl
 * @see cat.diba.materialesportiu.model.impl.LoanActivityModelImpl
 * @generated
 */
@ProviderType
public interface LoanActivityModel extends BaseModel<LoanActivity>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loan activity model instance should use the {@link LoanActivity} interface instead.
	 */

	/**
	 * Returns the primary key of this loan activity.
	 *
	 * @return the primary key of this loan activity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loan activity.
	 *
	 * @param primaryKey the primary key of this loan activity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loan activity ID of this loan activity.
	 *
	 * @return the loan activity ID of this loan activity
	 */
	public long getLoanActivityId();

	/**
	 * Sets the loan activity ID of this loan activity.
	 *
	 * @param loanActivityId the loan activity ID of this loan activity
	 */
	public void setLoanActivityId(long loanActivityId);

	/**
	 * Returns the loan ID of this loan activity.
	 *
	 * @return the loan ID of this loan activity
	 */
	public long getLoanId();

	/**
	 * Sets the loan ID of this loan activity.
	 *
	 * @param loanId the loan ID of this loan activity
	 */
	public void setLoanId(long loanId);

	/**
	 * Returns the activity ID of this loan activity.
	 *
	 * @return the activity ID of this loan activity
	 */
	public long getActivityId();

	/**
	 * Sets the activity ID of this loan activity.
	 *
	 * @param activityId the activity ID of this loan activity
	 */
	public void setActivityId(long activityId);

	/**
	 * Returns the quantity of this loan activity.
	 *
	 * @return the quantity of this loan activity
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this loan activity.
	 *
	 * @param quantity the quantity of this loan activity
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the group ID of this loan activity.
	 *
	 * @return the group ID of this loan activity
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this loan activity.
	 *
	 * @param groupId the group ID of this loan activity
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this loan activity.
	 *
	 * @return the company ID of this loan activity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loan activity.
	 *
	 * @param companyId the company ID of this loan activity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loan activity.
	 *
	 * @return the user ID of this loan activity
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loan activity.
	 *
	 * @param userId the user ID of this loan activity
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loan activity.
	 *
	 * @return the user uuid of this loan activity
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this loan activity.
	 *
	 * @param userUuid the user uuid of this loan activity
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loan activity.
	 *
	 * @return the user name of this loan activity
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loan activity.
	 *
	 * @param userName the user name of this loan activity
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loan activity.
	 *
	 * @return the create date of this loan activity
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loan activity.
	 *
	 * @param createDate the create date of this loan activity
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loan activity.
	 *
	 * @return the modified date of this loan activity
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loan activity.
	 *
	 * @param modifiedDate the modified date of this loan activity
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LoanActivity loanActivity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LoanActivity> toCacheModel();

	@Override
	public LoanActivity toEscapedModel();

	@Override
	public LoanActivity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}