/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cat.diba.materialesportiu.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Maintenance service. Represents a row in the &quot;PME_Maintenance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cat.diba.materialesportiu.model.impl.MaintenanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cat.diba.materialesportiu.model.impl.MaintenanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Maintenance
 * @see cat.diba.materialesportiu.model.impl.MaintenanceImpl
 * @see cat.diba.materialesportiu.model.impl.MaintenanceModelImpl
 * @generated
 */
@ProviderType
public interface MaintenanceModel extends BaseModel<Maintenance>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a maintenance model instance should use the {@link Maintenance} interface instead.
	 */

	/**
	 * Returns the primary key of this maintenance.
	 *
	 * @return the primary key of this maintenance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this maintenance.
	 *
	 * @param primaryKey the primary key of this maintenance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the maintenance ID of this maintenance.
	 *
	 * @return the maintenance ID of this maintenance
	 */
	public long getMaintenanceId();

	/**
	 * Sets the maintenance ID of this maintenance.
	 *
	 * @param maintenanceId the maintenance ID of this maintenance
	 */
	public void setMaintenanceId(long maintenanceId);

	/**
	 * Returns the activity ID of this maintenance.
	 *
	 * @return the activity ID of this maintenance
	 */
	public long getActivityId();

	/**
	 * Sets the activity ID of this maintenance.
	 *
	 * @param activityId the activity ID of this maintenance
	 */
	public void setActivityId(long activityId);

	/**
	 * Returns the label of this maintenance.
	 *
	 * @return the label of this maintenance
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this maintenance.
	 *
	 * @param label the label of this maintenance
	 */
	public void setLabel(String label);

	/**
	 * Returns the description of this maintenance.
	 *
	 * @return the description of this maintenance
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this maintenance.
	 *
	 * @param description the description of this maintenance
	 */
	public void setDescription(String description);

	/**
	 * Returns the start date of this maintenance.
	 *
	 * @return the start date of this maintenance
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this maintenance.
	 *
	 * @param startDate the start date of this maintenance
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this maintenance.
	 *
	 * @return the end date of this maintenance
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this maintenance.
	 *
	 * @param endDate the end date of this maintenance
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the is done of this maintenance.
	 *
	 * @return the is done of this maintenance
	 */
	public Boolean getIsDone();

	/**
	 * Sets the is done of this maintenance.
	 *
	 * @param isDone the is done of this maintenance
	 */
	public void setIsDone(Boolean isDone);

	/**
	 * Returns the loan ID of this maintenance.
	 *
	 * @return the loan ID of this maintenance
	 */
	public long getLoanId();

	/**
	 * Sets the loan ID of this maintenance.
	 *
	 * @param loanId the loan ID of this maintenance
	 */
	public void setLoanId(long loanId);

	/**
	 * Returns the group ID of this maintenance.
	 *
	 * @return the group ID of this maintenance
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this maintenance.
	 *
	 * @param groupId the group ID of this maintenance
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this maintenance.
	 *
	 * @return the company ID of this maintenance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this maintenance.
	 *
	 * @param companyId the company ID of this maintenance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this maintenance.
	 *
	 * @return the user ID of this maintenance
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this maintenance.
	 *
	 * @param userId the user ID of this maintenance
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this maintenance.
	 *
	 * @return the user uuid of this maintenance
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this maintenance.
	 *
	 * @param userUuid the user uuid of this maintenance
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this maintenance.
	 *
	 * @return the user name of this maintenance
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this maintenance.
	 *
	 * @param userName the user name of this maintenance
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this maintenance.
	 *
	 * @return the create date of this maintenance
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this maintenance.
	 *
	 * @param createDate the create date of this maintenance
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this maintenance.
	 *
	 * @return the modified date of this maintenance
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this maintenance.
	 *
	 * @param modifiedDate the modified date of this maintenance
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Maintenance maintenance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Maintenance> toCacheModel();

	@Override
	public Maintenance toEscapedModel();

	@Override
	public Maintenance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}