/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cat.diba.materialesportiu.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Material service. Represents a row in the &quot;PME_Material&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cat.diba.materialesportiu.model.impl.MaterialModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cat.diba.materialesportiu.model.impl.MaterialImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Material
 * @see cat.diba.materialesportiu.model.impl.MaterialImpl
 * @see cat.diba.materialesportiu.model.impl.MaterialModelImpl
 * @generated
 */
@ProviderType
public interface MaterialModel extends BaseModel<Material>, GroupedModel,
	LocalizedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a material model instance should use the {@link Material} interface instead.
	 */

	/**
	 * Returns the primary key of this material.
	 *
	 * @return the primary key of this material
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this material.
	 *
	 * @param primaryKey the primary key of this material
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the material ID of this material.
	 *
	 * @return the material ID of this material
	 */
	public long getMaterialId();

	/**
	 * Sets the material ID of this material.
	 *
	 * @param materialId the material ID of this material
	 */
	public void setMaterialId(long materialId);

	/**
	 * Returns the name of this material.
	 *
	 * @return the name of this material
	 */
	public String getName();

	/**
	 * Returns the localized name of this material in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this material
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this material in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this material. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this material in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this material
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this material in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this material
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this material.
	 *
	 * @return the locales and localized names of this material
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this material.
	 *
	 * @param name the name of this material
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this material in the language.
	 *
	 * @param name the localized name of this material
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this material in the language, and sets the default locale.
	 *
	 * @param name the localized name of this material
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this material from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this material
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this material from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this material
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the heigh of this material.
	 *
	 * @return the heigh of this material
	 */
	public float getHeigh();

	/**
	 * Sets the heigh of this material.
	 *
	 * @param heigh the heigh of this material
	 */
	public void setHeigh(float heigh);

	/**
	 * Returns the width of this material.
	 *
	 * @return the width of this material
	 */
	public float getWidth();

	/**
	 * Sets the width of this material.
	 *
	 * @param width the width of this material
	 */
	public void setWidth(float width);

	/**
	 * Returns the longitude of this material.
	 *
	 * @return the longitude of this material
	 */
	public float getLongitude();

	/**
	 * Sets the longitude of this material.
	 *
	 * @param longitude the longitude of this material
	 */
	public void setLongitude(float longitude);

	/**
	 * Returns the weight of this material.
	 *
	 * @return the weight of this material
	 */
	public float getWeight();

	/**
	 * Sets the weight of this material.
	 *
	 * @param weight the weight of this material
	 */
	public void setWeight(float weight);

	/**
	 * Returns the activity ID of this material.
	 *
	 * @return the activity ID of this material
	 */
	public long getActivityId();

	/**
	 * Sets the activity ID of this material.
	 *
	 * @param activityId the activity ID of this material
	 */
	public void setActivityId(long activityId);

	/**
	 * Returns the quantity of this material.
	 *
	 * @return the quantity of this material
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this material.
	 *
	 * @param quantity the quantity of this material
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the group ID of this material.
	 *
	 * @return the group ID of this material
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this material.
	 *
	 * @param groupId the group ID of this material
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this material.
	 *
	 * @return the company ID of this material
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this material.
	 *
	 * @param companyId the company ID of this material
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this material.
	 *
	 * @return the user ID of this material
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this material.
	 *
	 * @param userId the user ID of this material
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this material.
	 *
	 * @return the user uuid of this material
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this material.
	 *
	 * @param userUuid the user uuid of this material
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this material.
	 *
	 * @return the user name of this material
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this material.
	 *
	 * @param userName the user name of this material
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this material.
	 *
	 * @return the create date of this material
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this material.
	 *
	 * @param createDate the create date of this material
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this material.
	 *
	 * @return the modified date of this material
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this material.
	 *
	 * @param modifiedDate the modified date of this material
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(Material material);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Material> toCacheModel();

	@Override
	public Material toEscapedModel();

	@Override
	public Material toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}